// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQDMX7SRFbvY33BsvvfZzym26duMD7Ck',
    appId: '1:32110972454:web:b01653bbe197b1cd8720e7',
    messagingSenderId: '32110972454',
    projectId: 'project-d8c2e',
    authDomain: 'project-d8c2e.firebaseapp.com',
    storageBucket: 'project-d8c2e.firebasestorage.app',
    measurementId: 'G-8CNHW2SL6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgUW2NRJR0ygGM6yu2LLHAnXtp0Ojh9E',
    appId: '1:32110972454:android:0e3fba51a0fcb69a8720e7',
    messagingSenderId: '32110972454',
    projectId: 'project-d8c2e',
    storageBucket: 'project-d8c2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcbU5y5puU0qSN-QVVF6mdIruMgO87u0',
    appId: '1:32110972454:ios:2a62a903855fa8a88720e7',
    messagingSenderId: '32110972454',
    projectId: 'project-d8c2e',
    storageBucket: 'project-d8c2e.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgcbU5y5puU0qSN-QVVF6mdIruMgO87u0',
    appId: '1:32110972454:ios:2a62a903855fa8a88720e7',
    messagingSenderId: '32110972454',
    projectId: 'project-d8c2e',
    storageBucket: 'project-d8c2e.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQDMX7SRFbvY33BsvvfZzym26duMD7Ck',
    appId: '1:32110972454:web:97d4b26f7915365e8720e7',
    messagingSenderId: '32110972454',
    projectId: 'project-d8c2e',
    authDomain: 'project-d8c2e.firebaseapp.com',
    storageBucket: 'project-d8c2e.firebasestorage.app',
    measurementId: 'G-LFDQGN5M53',
  );
}
